Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/raspberry/RPC-client-server/new_ArmPiClient/RPCServer.py", line 94, in startRPCServer
    run_simple("", 9030, application)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 862, in make_server
    return BaseWSGIServer(
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
strat Armpi RPC
strat Armpi RPC
Traceback (most recent call last):
  File "/home/raspberry/RPC-client-server/new_ArmPiClient/ArmPiClient.py", line 119, in <module>
    startClientRPC()
  File "/home/raspberry/RPC-client-server/new_ArmPiClient/ArmPiClient.py", line 31, in startClientRPC
    time.sleep(0.005)
KeyboardInterrupt
